### ISSUE TITLE
Survey people to understand how they perceive heat risk

### ISSUE THREAD

**Issue by Rainie34** [zatonovo/cadp_docs#6]
Here  is our link of the survey.
https://docs.google.com/forms/d/e/1FAIpQLSf_FvqEy2Yrdyqf9J911ZZoh6VZT6hvb0HgvLHeS8qYNxNNvw/viewform?usp=sf_link

**Comment by Rainie34** [comment]
@muxspace ,Hi Prof. Rowe, please review our survey.

**Comment by muxspace** [comment]
@Rainie34 I need permission to view the survey. Please add my email address.

**Comment by muxspace** [comment]
I can access vi YU address

**Comment by muxspace** [comment]
@Rainie34 @vidhika-git the application of the scientific method is supposed to be reflected in the survey. Basically all of the research (background reading) you two did is supposed to inform the survey questions.

Ultimately you need to answer:

- What are the hypotheses you have regarding the people responding to the survey?
- How do the survey questions help test these hypotheses?
- Based on the results of the survey, what type of questions should the AI advisor be trained to answer?

**Comment by muxspace** [comment]
## Applying the scientific method 
Background reading provides context regarding the state of the art. You should be able to identify gaps in knowledge or current limitations that need to be explored.

The survey allows you to test some hypotheses. In this case about extreme heat and how different populations are either affected deal with it.

The purpose of the anecdotes was to give you ideas regarding how people are affected by extreme heat and how they to respond to it, and what are some of the challenges they face.

**Comment by muxspace** [comment]
## Questions to hypotheses to surveys

Start with an open question that needs to be answered. Then formulate a hypothesis (your guess about the answer to the question). Then determine how to test the hypothesis. A survey is one approach (not always appropriate).

Question: Do people know what the symptoms of heat stress are?
Hypothesis (vidhika): No, they don't know
Hypothesis (yu): Yes they know that dizziness is a symptom of heat stress

What survey question(s) can test this hypothesis?

- have you ever felt the effects of heat stress? If so, what symptoms did you experience?
- have you ever felt dizzy in hot temperatures? <- this only checks what they've experienced, not what they know
- do you think that dizziness is a symptom of heat stress? <- we expect yes
- do you think memory loss a symptom of heat stress? <- we expect no
- which of the following states are possible symptoms of heat stress? 
  - dizziness
  - memory loss
  - dark yellow urine
  - fatigue
  - confusion
  - happiness
  - clarity
  - low body temperature
  - boredom

This last question can test a whole number of potential symptoms simultaneously in a survey. So it's a bit faster than single questions.

**Comment by muxspace** [comment]
Documentation prior to creating survey justifies the questions being asked in the survey. So all that research is providing the context to justify what questions you're asking and what you think the answers are (the hypotheses).

**Comment by muxspace** [comment]
For 9 October, 2024 do another iteration and target a specific demographic based on what you read. Indicate 

- why that demographic is important, i.e., why there is a need for an AI heat advisor to help that demographic
- what issues they face regarding extreme heat

Include the links in the document (references).

**Comment by vidhika-git** [comment]
Awareness of Heat Stress Symptoms
Hypothesis:  significant portion of the community lacks awareness of the symptoms of heat stress, which may increase their risk of heat-related illnesses during extreme heat events.
Survey Questions:

1. Which of the following do you believe are symptoms of heat stress? (Select all that apply)

- Dizziness
- Nausea
- Headache
- Sweating
- Confusion
- Fever
- slow and calm breathing
- good vision
- I don’t know

2. Have you ever experienced any symptoms of heat stress? If so, which ones?

-  Open-ended response
 3. Which symptoms do you think are most serious during extreme heat? (Select all that apply)

 
-  Heat exhaustion
- Heat stroke
- Dehydration
- Other (please specify)
  
4. Have you ever seen information about heat stress symptoms in public health materials?

- Yes
- No

5. How confident are you in your ability to identify the symptoms of heat stress?

- Very confident
- Somewhat confident
- Not confident


** This is the sample hypothesis and question please find the rest of the in the Word document**

**Comment by vidhika-git** [comment]
As assigned by @muxspace  
do another iteration and target a specific demographic based on what you read. Indicate
why that demographic is important, i.e., why there is a need for an AI heat advisor to help that demographic
with what issues they face regarding extreme heat

Demographic-based target a specific demographic - **older adults**
Link - https://www.heat.gov/pages/who-is-at-risk-to-extreme-heat

Hypothesis
Older adults face increased health risks during extreme heat events due to underlying medical conditions, social isolation, and limited access to cooling resources.

Importance of Targeting Older Adults

- Health Vulnerabilities
- Dependence on Medical Equipment
- Social Isolation

### Survey Questions
**Demographic Information:**

1. What is your age?

2.  Do you live alone?
- live alone, 
- with family
-  community setting?

 **Health Status:**

3. Do you have any chronic health conditions? (e.g., heart disease, diabetes, respiratory issues)
4. Are you currently taking any medications that may affect your ability to regulate body temperature?


**Access to Cooling Resources:**

5. Do you have air conditioning in your home? If not, what cooling methods do you use?


**Social Connections:**

6. How often do you interact with friends or family members?

- very often (3-4  time a week)
- often ( like once or twice on week)
- occasionally
- rarely
- very rarely 

7. Do you have someone you can rely on for help during a heat wave?

- Yes 
- No

**Awareness and Preparedness:**

8. Are you aware of the risks associated with extreme heat?

- Yes
- No

9. What strategies do you currently use to stay cool during hot weather?

**Technology Use:**

10. Do you currently use any health or weather-related apps on your phone or device?

- Yes
- No

11. Would you be interested in using an AI heat advisor for personalized advice on staying safe during extreme heat?

- Yes
- No

**Comment by Rainie34** [comment]
@muxspace  here is our new survey, please review. https://docs.google.com/forms/d/e/1FAIpQLSczMgPBdWPWfhj69nJX0v1IQx8Z6YhwAdJY9e8OHbEFKtZ8bQ/viewform?usp=sf_link

**Comment by muxspace** [comment]
@Rainie34 please define the questions/hypotheses you are attempting to answer with the survey.

**Comment by muxspace** [comment]
All new discussion should occur in [the card creating the survey](https://github.com/orgs/zatonovo/projects/8/views/1?pane=issue&itemId=82822511&issue=zatonovo%7Czeomancer_system%7C53)
